# Fonts
font_family Fira Code
symbol_map U+E0A0-U+E0A2,U+E0B0-U+E0B3 FuraCode Nerd Font

font_size 20.0

# Cursor
cursor_blink_interval 0

# Terminal bell
enable_audio_bell no

# Tweaks
window_padding_width 5
macos_thicken_font 0.2
macos_titlebar_color background
copy_on_select yes
macos_option_as_alt both
open_url_modifiers kitty_mod
kitty_mod cmd

include ./theme.conf

